// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { resolve } from "path";

// Fallback pour DATABASE_URL si non défini
if (!process.env.DATABASE_URL) {
  const dbPath = resolve(process.cwd(), "dev.db");
  process.env.DATABASE_URL = `file:${dbPath}`;
}

// Configuration Prisma simplifiée (sans defineConfig qui n'existe pas dans cette version)
// Ce fichier est utilisé uniquement pour définir DATABASE_URL
// La configuration Prisma se fait via prisma/schema.prisma
